volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 15

  backend:
    image: goodwiine/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - foodgram_network
    command: 
      sh -c "
        python manage.py migrate --noinput && 
        python manage.py collectstatic --noinput && 
        gunicorn foodgram.wsgi:application --bind 0.0.0.0:8080
      "

  frontend:
    image: goodwiine/foodgram_frontend:latest
    volumes:
      - frontend_build:/app/build
    networks:
      - foodgram_network
    restart: "no"
    depends_on:
      - backend

  gateway:
    image: goodwiine/foodgram_gateway:latest
    ports:
      - "8080:80"
    volumes:
      - static:/app/static
      - media:/app/media
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network

networks:
  foodgram_network:
    driver: bridge