# Generated by Django 3.2.16 on 2026-02-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name='Слаг для короткой ссылки'),
        ),
    ]
