# Generated by Django 3.2.16 on 2026-02-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shortlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
