# Generated by Django 3.2.16 on 2026-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260213_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
